###

# curl -X 'GET' 
#  'https://localhost:5050/periods?PageIndex=0&PageSize=10' 
#  -H 'accept: application/json'
GET {{API_HostAddress}}/periods?PageIndex=0&PageSize=10
accept: application/json

###

# curl -X 'POST' 
#  'https://localhost:5050/periods' 
#  -H 'accept: application/json' 
#  -H 'Content-Type: application/json' 
#  -d '{
#  "period": {
#    "companyId": "41607051-4bd8-4a54-a5e2-cb713aef6ca2"
#  }
#}'
POST {{API_HostAddress}}/periods
accept: application/json
Content-Type: application/json

{
  "periodId": "b4bc65ca-0879-4014-bc42-2ed747619529"
}

###

# curl -X 'PUT' 
#  'https://localhost:5050/periods/close' 
#  -H 'accept: application/json' 
#  -H 'Content-Type: application/json' 
#  -d '{
#  "period": {
#    "periodId": "e44ed594-272c-4978-a3b5-11fb47e9ca12",
#    "companyId": "41607051-4bd8-4a54-a5e2-cb713aef6ca2"
#  }
#}'
PUT {{API_HostAddress}}/periods/close
accept: application/json
Content-Type: application/json

{
  "period": {
    "periodId": "e44ed594-272c-4978-a3b5-11fb47e9ca12",
    "companyId": "41607051-4bd8-4a54-a5e2-cb713aef6ca2"
  }
}

###

# curl -X 'GET' 
#  'https://localhost:5050/periods/year=2025&month=7' 
#  -H 'accept: application/json'
GET {{API_HostAddress}}/periods/year=2025&month=8
accept: application/json

###

# curl -X 'GET' 
#  'https://localhost:5050/periods/e44ed594-272c-4978-a3b5-11fb47e9ca12' 
#  -H 'accept: application/json'
GET {{API_HostAddress}}/periods/e44ed594-272c-4978-a3b5-11fb47e9ca12
accept: application/json

###

GET {{API_HostAddress}}/periods/open
accept: application/json

###

# curl -X 'PUT' 
#  'https://localhost:5050/periods/e44ed594-272c-4978-a3b5-11fb47e9ca12/close' 
#  -H 'accept: application/json'
PUT {{API_HostAddress}}/periods/e44ed594-272c-4978-a3b5-11fb47e9ca12/close
accept: application/json

###

# curl -X 'PUT' 
#  'https://localhost:5050/periods/open' 
#  -H 'accept: application/json' 
#  -H 'Content-Type: application/json' 
#  -d '{
#  "period": {
#    "periodId": "e44ed594-272c-4978-a3b5-11fb47e9ca12",
#    "companyId": "41607051-4bd8-4a54-a5e2-cb713aef6ca2"
#  }
#}'
PUT {{API_HostAddress}}/periods/open
accept: application/json
Content-Type: application/json

{
  "period": {
    "periodId": "e44ed594-272c-4978-a3b5-11fb47e9ca12",
    "companyId": "41607051-4bd8-4a54-a5e2-cb713aef6ca2"
  }
}

###

# curl -X 'POST' 
#  'https://localhost:5050/journal-entries' 
#  -H 'accept: application/json' 
#  -H 'Content-Type: application/json' 
#  -d '{
#  "journalEntry": {
#    "date": "2025-08-01T02:26:27.053Z",
#    "description": "Registro de ventas demo.",
#    "periodId": "e44ed594-272c-4978-a3b5-11fb47e9ca12",
#    "companyId": "41607051-4bd8-4a54-a5e2-cb713aef6ca2",
#    "currencyCode": "CRC",
#    "exchangeRate": 0,
#    "exchangeRateDate": "2025-08-14",    
#    "lines": [
#      {
#        "accountId": "7573e77c-110b-4a3b-9bda-7be306bb14b4",
#        "debit": 4000,
#        "credit": 0,
#        "lineNumber": 1
##      },
##      {
##        "accountId": "cacfc56f-82ca-4cd5-b694-540b5e1b2e03",
##        "debit": 0,
##        "credit": 4000,
##        "lineNumber": 2
##      }
##    ]
##  }
#}'
POST https://localhost:5050/journal-entries
accept: application/json
Content-Type: application/json

{
  "journalEntry": {
    "date": "2025-08-01T02:26:27.053Z",
    "description": "Registro de ventas demo.",
    "periodId": "e44ed594-272c-4978-a3b5-11fb47e9ca12",
    "companyId": "41607051-4bd8-4a54-a5e2-cb713aef6ca2",
    "currencyCode": "CRC",
    "exchangeRate": 0,
    "exchangeRateDate": "2025-08-14",    
    "lines": [
      {
        "accountId": "7573e77c-110b-4a3b-9bda-7be306bb14b4",
        "debit": 4000,
        "credit": 0,
        "lineNumber": 1
      },
      {
        "accountId": "cacfc56f-82ca-4cd5-b694-540b5e1b2e03",
        "debit": 0,
        "credit": 4000,
        "lineNumber": 2
      }
    ]
  }
}

###

# curl -X 'GET' 
#  'https://localhost:5050/periods/e44ed594-272c-4978-a3b5-11fb47e9ca12' 
#  -H 'accept: application/json'
GET {{API_HostAddress}}/periods/e44ed594-272c-4978-a3b5-11fb47e9ca12
accept: application/json

###

# curl -X 'POST' 
#  'https://localhost:5050/journal-entries' 
#  -H 'accept: application/json' 
#  -H 'Content-Type: application/json' 
#  -d '{
#  "journalEntry": {
#    "date": "2025-08-01T02:26:27.053Z",
#    "description": "Registro de ventas de contado.",
#    "periodId": "e44ed594-272c-4978-a3b5-11fb47e9ca12",
#    "companyId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
#    "currencyCode": "string",
#    "exchangeRate": 0,
#    "exchangeRateDate": "2025-08-14",
#    "isPosted": true,
#    "isReversed": true,
#    "lines": [
#      {
#        "accountId": "7573e77c-110b-4a3b-9bda-7be306bb14b4",
#        "debit": 4000,
#        "credit": 0,
#        "lineNumber": 1
#      },
#      {
#        "accountId": "cacfc56f-82ca-4cd5-b694-540b5e1b2e03",
#        "debit": 0,
#        "credit": 4000,
#        "lineNumber": 1
#      }	  
#    ]
#  }
#}'
POST {{API_HostAddress}}/journal-entries
accept: application/json
Content-Type: application/json

{
  "journalEntry": {
    "date": "2025-08-01T02:26:27.053Z",
    "description": "Registro de ventas demo.",
    "periodId": "e44ed594-272c-4978-a3b5-11fb47e9ca12",
    "companyId": "41607051-4bd8-4a54-a5e2-cb713aef6ca2",
    "currencyCode": "CRC",
    "exchangeRate": 0,
    "exchangeRateDate": "2025-08-14",    
    "lines": [
      {
        "accountId": "7573e77c-110b-4a3b-9bda-7be306bb14b4",
        "debit": 4000,
        "credit": 0,
        "lineNumber": 1
      },
      {
        "accountId": "cacfc56f-82ca-4cd5-b694-540b5e1b2e03",
        "debit": 0,
        "credit": 4000,
        "lineNumber": 2
      }
    ]
  }
}

###




















###

# curl -X 'PUT' 
#  'https://localhost:5050/companies' 
#  -H 'accept: application/json' 
#  -H 'Content-Type: application/json' 
#  -d '{
#  "company": {
#        "id": "9429a754-221f-45ca-aeeb-f8b443157831",
#        "name": "Demo",
#        "taxId": "3101268467",
#        "country": "CR",
#        "currencyCode": "USD",
#        "isActive": false
#  }
#}'
PUT {{API_HostAddress}}/companies
accept: application/json
Content-Type: application/json

{
  "company": {
    "id": "9429a754-221f-45ca-aeeb-f8b443157831",
    "name": "Demo1",
    "taxId": "3101268467",
    "country": "CR",
    "currencyCode": "USD",
    "isActive": false
  }
}

###

# curl -X 'POST' 
#  'https://localhost:5050/companies' 
#  -H 'accept: application/json' 
#  -H 'Content-Type: application/json' 
#  -d '{
#  "account": {
#    "name": "Demo",
#    "taxId": "3101268467",
#    "country": "CR",
#    "currencyCode": "USD",
#    "isActive": true
#  }
#}'
POST {{API_HostAddress}}/companies
accept: application/json
Content-Type: application/json

{
  "company": {
    "name": "Demo",
    "taxId": "3101268467",
    "country": "CR",
    "currencyCode": "USD",
    "isActive": true
  }
}

###

# curl -X 'GET' 
#  'https://localhost:5050/companies/41607051-4bd8-4a54-a5e2-cb713aef6ca2' 
#  -H 'accept: application/json'
GET {{API_HostAddress}}/companies/41607051-4bd8-4a54-a5e2-cb713aef6ca2
accept: application/json

###

# curl -X 'GET' 
#  'https://localhost:5050/companies?PageIndex=0&PageSize=10' 
#  -H 'accept: application/json'
GET {{API_HostAddress}}/companies?PageIndex=0&PageSize=10
accept: application/json

###

# curl -X 'POST' 
#  'https://localhost:5050/currencies' 
#  -H 'accept: application/json' 
#  -H 'Content-Type: application/json' 
#  -d '{
#  "currencyExchangeRate": {
#    "currencyCode": "USD",
#    "date": "2025-08-10",
#    "buyRate": 500,
#    "sellRate": 514
#  }
#}
POST {{API_HostAddress}}/currencies
accept: application/json
Content-Type: application/json

{
  "currencyExchangeRate": {
    "currencyCode": "USD",
    "date": "2025-08-11",
    "buyRate": 500,
    "sellRate": 514
  }
}

###

# curl -X 'GET' 
#  'https://localhost:5050/currencies/daily' 
#  -H 'accept: application/json'
GET {{API_HostAddress}}/currencies/daily
accept: application/json

###

# curl -X 'GET' 
#  'https://localhost:5050/currencies?PageIndex=0&PageSize=10' 
#  -H 'accept: application/json'
GET {{API_HostAddress}}/currencies?PageIndex=0&PageSize=10
accept: application/json

###

# curl -X 'PUT' 
#  'https://localhost:5050/journal-entries3d5eeef9-d3a9-43e4-9b60-dd4a16e20ba7/reverse' 
#  -H 'accept: application/json'
PUT {{API_HostAddress}}/journal-entries3d5eeef9-d3a9-43e4-9b60-dd4a16e20ba7/reverse
accept: application/json

###

# curl -X 'DELETE' 
#  'https://localhost:5050/journal-entries/896dd1df-1413-4098-bbbd-d5586cb8f86e' 
#  -H 'accept: application/json'
DELETE {{API_HostAddress}}/journal-entries/896dd1df-1413-4098-bbbd-d5586cb8f86e
accept: application/json

###

# curl -X 'GET' 
#  'https://localhost:5050/journal-entries/56cb166e-07b6-44f7-bd8b-cbc16c595946' 
#  -H 'accept: application/json'
GET {{API_HostAddress}}/journal-entries/56cb166e-07b6-44f7-bd8b-cbc16c595946
accept: application/json

###

# curl -X 'GET' 
#  'https://localhost:5050/journal-entries?PageIndex=0&PageSize=10' 
#  -H 'accept: application/json'
GET {{API_HostAddress}}/journal-entries?PageIndex=0&PageSize=10
accept: application/json

###

# curl -X 'PUT' 
#  'https://localhost:5050/journal-entries' 
#  -H 'accept: application/json' 
#  -H 'Content-Type: application/json' 
#  -d '{
#  "journalEntry": {
#    "id": "b2d06aa7-3ae6-4741-93ac-68e1d900a262",
#    "date": "2025-08-01T02:26:27.053Z",
#    "description": "Registro de ventas por contado.",
#    "isReversed": true,
#    "periodId": "e44ed594-272c-4978-a3b5-11fb47e9ca12",
#    "lines": [
#      {
#        "id": "98723cc8-2f31-40a1-a4b0-aeb6ff085f86",
#        "journalEntryId": "b2d06aa7-3ae6-4741-93ac-68e1d900a262",
#        "accountId": "7573e77c-110b-4a3b-9bda-7be306bb14b4",
#        "debit": 5000
#        "credit": 0,
#        "lineNumber": 1
#      },
#      {
#        "id": "f3d8e587-6492-490d-823d-d1bffdf390fe",
#        "journalEntryId": "b2d06aa7-3ae6-4741-93ac-68e1d900a262",
#        "accountId": "cacfc56f-82ca-4cd5-b694-540b5e1b2e03",
#        "debit": 0,
#        "credit": 5000
#        "lineNumber": 2
#      }	  
#    ]
#  }
#}'
PUT {{API_HostAddress}}/journal-entries
accept: application/json
Content-Type: application/json

{
  "journalEntry": {
    "id": "31c86b11-a2ca-40c3-8312-493c874d9c18",
    "date": "2025-08-01T02:26:27.053Z",
    "description": "Registro de ventas por contado demo.",
    "isReversed": true,
    "periodId": "e44ed594-272c-4978-a3b5-11fb47e9ca12",
    "lines": [
      {
        "journalEntryId": "31c86b11-a2ca-40c3-8312-493c874d9c18",
        "accountId": "7573e77c-110b-4a3b-9bda-7be306bb14b4",
        "debit": 50000,
        "credit": 0,
        "lineNumber": 1
      },
      {
        "journalEntryId": "31c86b11-a2ca-40c3-8312-493c874d9c18",
        "accountId": "cacfc56f-82ca-4cd5-b694-540b5e1b2e03",
        "debit": 0,
        "credit": 50000,
        "lineNumber": 2
      }
    ]
  }
}

###


# curl -X 'GET' 
#  'https://localhost:5050/journal-entries/3fa85f64-5717-4562-b3fc-2c963f66afa6/documents' 
#  -H 'accept: application/json'
GET {{API_HostAddress}}/journal-entries/0b55189d-ce04-471f-abbb-f73208be063a/documents
accept: application/json

###

# curl -X 'GET' 
#  'https://localhost:5050/audit-logs?PageIndex=0&PageSize=10' 
#  -H 'accept: application/json'
GET {{API_HostAddress}}/audit-logs?PageIndex=0&PageSize=10
accept: application/json

###

# curl -X 'GET' 
#  'https://localhost:5050/audit-logs/e44ed594-272c-4978-a3b5-11fb47e9ca12' 
#  -H 'accept: application/json'
GET {{API_HostAddress}}/audit-logs/e44ed594-272c-4978-a3b5-11fb47e9ca12
accept: application/json

###

# curl -X 'PUT' 
#  'https://localhost:5050/accounts' 
#  -H 'accept: application/json' 
#  -H 'Content-Type: application/json' 
#  -d '{
#  "account": {
#    "id": "00445bc5-6287-4b1c-8af9-76df7fb37ac2",
#    "code": "7006",
#    "name": "Gastos varios",
#    "accountTypeId": "71bbd6e0-abf4-4f2a-afec-9199bb404b08",
#    "isActive": true
#  }
#}'
PUT {{API_HostAddress}}/accounts
accept: application/json
Content-Type: application/json

{
  "accountDetail": {
    "id": "00445bc5-6287-4b1c-8af9-76df7fb37ac2",
    "code": "7006",
    "name": "Gastos varios de segundo nivel",
    "accountTypeId": "71bbd6e0-abf4-4f2a-afec-9199bb404b08",
    "parentAccountId": "8c597200-7580-4494-87b2-4661becf8690",
    "isActive": false
  }
}

###

# curl -X 'DELETE' 
#  'https://localhost:5050/accounts/0065ecee-ee6b-4d42-bb8b-0e24b20c213f' 
#  -H 'accept: application/json'
DELETE {{API_HostAddress}}/accounts/12bc88ce-fb30-4107-8da8-de6cbe4a5300
accept: application/json

###

# curl -X 'POST' 
#  'https://localhost:5050/accounts' 
#  -H 'accept: application/json' 
#  -H 'Content-Type: application/json' 
#  -d '{
#  "account": {
#    "code": "7001",
#    "name": "Gastos varios",
#    "accountTypeId": "71bbd6e0-abf4-4f2a-afec-9199bb404b08"
#  }
#}'
POST {{API_HostAddress}}/accounts
accept: application/json
Content-Type: application/json

{
  "account": {
    "name": "Patentes y permisos municipales",
    "accountTypeId": "71bbd6e0-abf4-4f2a-afec-9199bb404b08",
    "ParentAccountId": "15165f65-a55a-4f7c-8d87-9275301217af"
  }
}

###

# curl -X 'GET' 
#  'https://localhost:5050/accounts?PageIndex=1&PageSize=10' 
#  -H 'accept: application/json'
GET {{API_HostAddress}}/accounts?PageIndex=0&PageSize=10
accept: application/json

###

# curl -X 'PUT' 
#  'https://localhost:5050/accounts/cacfc56f-82ca-4cd5-b694-540b5e1b2e03/desactivate' 
#  -H 'accept: application/json'
PUT {{API_HostAddress}}/accounts/cacfc56f-82ca-4cd5-b694-540b5e1b2e03/desactivate
accept: application/json

###

# curl -X 'PUT' 
#  'https://localhost:5050/accounts/cacfc56f-82ca-4cd5-b694-540b5e1b2e03/activate' 
#  -H 'accept: application/json'
PUT {{API_HostAddress}}/accounts/cacfc56f-82ca-4cd5-b694-540b5e1b2e03/activate
accept: application/json

###

# curl -X 'GET' 
#  'https://localhost:5050/accounts/types' 
#  -H 'accept: application/json'
GET {{API_HostAddress}}/accounts/types
accept: application/json

###

# curl -X 'GET' 
#  'https://localhost:5050/accounts/tree' 
#  -H 'accept: application/json'
GET {{API_HostAddress}}/accounts/tree
accept: application/json

###

# curl -i http://httpbin.org/ip
GET {{API_HostAddress}}/health

###
