# curl -X 'GET' 
#  'https://localhost:5050/api/accounts/types' 
#  -H 'accept: application/json'
GET {{API_HostAddress}}/api/accounts/types
accept: application/json

###

# curl -i http://httpbin.org/ip
GET {{API_HostAddress}}/health

###
