# curl -X 'POST' 
#  'https://localhost:5050/accounts' 
#  -H 'accept: application/json' 
#  -H 'Content-Type: application/json' 
#  -d '{
#  "account": {
#    "code": "7001",
#    "name": "Gastos varios",
#    "accountTypeId": "71bbd6e0-abf4-4f2a-afec-9199bb404b08"
#  }
#}'
POST https://localhost:5050/accounts
accept: application/json
Content-Type: application/json

{
  "account": {
    "code": "7001",
    "name": "Gastos varios",
    "accountTypeId": "71bbd6e0-abf4-4f2a-afec-9199bb404b08"
  }
}

###

# curl -X 'GET' 
#  'https://localhost:5050/accounts?PageIndex=1&PageSize=10' 
#  -H 'accept: application/json'
GET {{API_HostAddress}}/accounts?PageIndex=0&PageSize=10
accept: application/json

###

# curl -X 'PUT' 
#  'https://localhost:5050/accounts/cacfc56f-82ca-4cd5-b694-540b5e1b2e03/desactivate' 
#  -H 'accept: application/json'
PUT {{API_HostAddress}}/accounts/cacfc56f-82ca-4cd5-b694-540b5e1b2e03/desactivate
accept: application/json

###

# curl -X 'PUT' 
#  'https://localhost:5050/accounts/cacfc56f-82ca-4cd5-b694-540b5e1b2e03/activate' 
#  -H 'accept: application/json'
PUT {{API_HostAddress}}/accounts/cacfc56f-82ca-4cd5-b694-540b5e1b2e03/activate
accept: application/json

###

# curl -X 'GET' 
#  'https://localhost:5050/accounts/types' 
#  -H 'accept: application/json'
GET {{API_HostAddress}}/accounts/types
accept: application/json

###

# curl -i http://httpbin.org/ip
GET {{API_HostAddress}}/health

###
