### The objective of this file is to create a complete test flow for integration testing.

# 1. Create a company
POST {{API_HostAddress}}/companies
accept: application/json
Content-Type: application/json

{
  "company": {
    "name": "MBC S.A.",
    "taxId": "3101267456",
    "country": "CR",
    "currencyCode": "CRC",
    "isActive": true
  }
}

###

# 2. Create accounting period
POST {{API_HostAddress}}/periods
accept: application/json
Content-Type: application/json

{
  "period": {
    "companyId": "b8420596-1834-41b5-a3f6-621e5a0a42c6"
  }
}

###

# 3. Create exchange rate
POST {{API_HostAddress}}/currencies
accept: application/json
Content-Type: application/json

{
  "currencyExchangeRate": {
    "currencyCode": "USD",
    "date": "2025-08-26",
    "buyRate": 496,
    "sellRate": 510
  }
}

###

# 4. Journal Entries
POST {{API_HostAddress}}/journal-entries
accept: application/json
Content-Type: application/json

{
  "journalEntry": {
    "date": "2025-08-01T02:26:27.053Z",
    "description": "Aporte de capital de tres socios e la empresa.",
    "periodId": "b1b451fc-28e2-44a1-b283-7dfe8957c839",
    "companyId": "b8420596-1834-41b5-a3f6-621e5a0a42c6",
    "currencyCode": "CRC",
    "exchangeRate": 0,
    "exchangeRateDate": "2025-08-14",
    "lines": [
      {
        "accountId": "23b79d9f-96d3-4c20-ac8e-4387a70152b3",
        "debit": 45000000,
        "credit": 0,
        "lineNumber": 1
      },
      {
        "accountId": "a91a4d34-c88e-4f29-8e31-03986820bada",
        "debit": 0,
        "credit": 45000000,
        "lineNumber": 2
      }
    ]
  }
}

###

POST {{API_HostAddress}}/journal-entries
accept: application/json
Content-Type: application/json

{
  "journalEntry": {
    "date": "2025-08-02T02:26:27.053Z",
    "description": "Pago de alquiler de tres meses de la empresa.",
    "periodId": "b1b451fc-28e2-44a1-b283-7dfe8957c839",
    "companyId": "b8420596-1834-41b5-a3f6-621e5a0a42c6",
    "currencyCode": "CRC",
    "exchangeRate": 0,
    "exchangeRateDate": "2025-08-02",
    "lines": [
      {
        "accountId": "043c84a8-3590-4b89-b439-7d3e540afba9",
        "debit": 600000,
        "credit": 0
      },
      {
        "accountId": "23b79d9f-96d3-4c20-ac8e-4387a70152b3",
        "debit": 0,
        "credit": 600000
      }
    ]
  }
}

###

POST {{API_HostAddress}}/journal-entries
accept: application/json
Content-Type: application/json

{
  "journalEntry": {
    "date": "2025-08-05T02:26:27.053Z",
    "description": "Compra de insumos al contado y al credito.",
    "periodId": "b1b451fc-28e2-44a1-b283-7dfe8957c839",
    "companyId": "b8420596-1834-41b5-a3f6-621e5a0a42c6",
    "currencyCode": "CRC",
    "exchangeRate": 0,
    "exchangeRateDate": "2025-08-02",
    "lines": [
      {
        "accountId": "d29ece51-323d-4c36-9193-9bbf3b04b962",
        "debit": 2000000,
        "credit": 0
      },
      {
        "accountId": "23b79d9f-96d3-4c20-ac8e-4387a70152b3",
        "debit": 0,
        "credit": 600000
      },
      {
        "accountId": "a04ee151-03d4-4840-8697-600360d6977d",
        "debit": 0,
        "credit": 1400000
      }      
    ]
  }
}

###

POST {{API_HostAddress}}/journal-entries
accept: application/json
Content-Type: application/json

{
  "journalEntry": {
    "date": "2025-08-15T02:26:27.053Z",
    "description": "Pago primera quincena de salario.",
    "periodId": "b1b451fc-28e2-44a1-b283-7dfe8957c839",
    "companyId": "b8420596-1834-41b5-a3f6-621e5a0a42c6",
    "currencyCode": "CRC",
    "exchangeRate": 0,
    "exchangeRateDate": "2025-08-15",
    "lines": [
      {
        "accountId": "e769d46b-268d-463c-8074-71983ead323f",
        "debit": 500000,
        "credit": 0
      },
      {
        "accountId": "23b79d9f-96d3-4c20-ac8e-4387a70152b3",
        "debit": 0,
        "credit": 500000
      }
    ]
  }
}

###

POST {{API_HostAddress}}/journal-entries
accept: application/json
Content-Type: application/json

{
  "journalEntry": {
    "date": "2025-08-19T02:26:27.053Z",
    "description": "Pago de servicios publicos del mes.",
    "periodId": "b1b451fc-28e2-44a1-b283-7dfe8957c839",
    "companyId": "b8420596-1834-41b5-a3f6-621e5a0a42c6",
    "currencyCode": "CRC",
    "exchangeRate": 0,
    "exchangeRateDate": "2025-08-19",
    "lines": [
      {
        "accountId": "e19f4576-6224-40e3-8b03-01343b413df7",
        "debit": 150000,
        "credit": 0
      },
      {
        "accountId": "23b79d9f-96d3-4c20-ac8e-4387a70152b3",
        "debit": 0,
        "credit": 150000
      }
    ]
  }
}

###

POST {{API_HostAddress}}/journal-entries
accept: application/json
Content-Type: application/json

{
  "journalEntry": {
    "date": "2025-08-26T02:26:27.053Z",
    "description": "Venta de servicios de jardineria por un 30% contado y el resto al credito.",
    "periodId": "b1b451fc-28e2-44a1-b283-7dfe8957c839",
    "companyId": "b8420596-1834-41b5-a3f6-621e5a0a42c6",
    "currencyCode": "CRC",
    "exchangeRate": 0,
    "exchangeRateDate": "2025-08-26",
    "lines": [
      {
        "accountId": "23b79d9f-96d3-4c20-ac8e-4387a70152b3",
        "debit": 320000,
        "credit": 0
      },
      {
        "accountId": "797cc7bd-99f4-4f77-a8d6-9a0e30c152bf",
        "debit": 480000,
        "credit": 0
      },
      {
        "accountId": "b33d3d96-4b34-44ae-9fe5-2fc8d657b115",
        "debit": 0,
        "credit": 800000
      }
    ]
  }
}

###

POST {{API_HostAddress}}/journal-entries
accept: application/json
Content-Type: application/json

{
  "journalEntry": {
    "date": "2025-08-27T02:26:27.053Z",
    "description": "Abono a la cuenta por pagar.",
    "periodId": "b1b451fc-28e2-44a1-b283-7dfe8957c839",
    "companyId": "b8420596-1834-41b5-a3f6-621e5a0a42c6",
    "currencyCode": "CRC",
    "exchangeRate": 0,
    "exchangeRateDate": "2025-08-27",
    "lines": [
      {
        "accountId": "a04ee151-03d4-4840-8697-600360d6977d",
        "debit": 500000,
        "credit": 0
      },
      {
        "accountId": "23b79d9f-96d3-4c20-ac8e-4387a70152b3",
        "debit": 0,
        "credit": 500000
      }
    ]
  }
}

###

POST {{API_HostAddress}}/journal-entries
accept: application/json
Content-Type: application/json

{
  "journalEntry": {
    "date": "2025-08-28T02:26:27.053Z",
    "description": "Abono de cliente a la cuenta por cobrar.",
    "periodId": "b1b451fc-28e2-44a1-b283-7dfe8957c839",
    "companyId": "b8420596-1834-41b5-a3f6-621e5a0a42c6",
    "currencyCode": "CRC",
    "exchangeRate": 0,
    "exchangeRateDate": "2025-08-28",
    "lines": [
      {
        "accountId": "23b79d9f-96d3-4c20-ac8e-4387a70152b3",
        "debit": 150000,
        "credit": 0
      },
      {
        "accountId": "797cc7bd-99f4-4f77-a8d6-9a0e30c152bf",
        "debit": 0,
        "credit": 150000
      }
    ]
  }
}

###

# 5. Reversal
PUT {{API_HostAddress}}/journal-entries/b5b78718-127d-40cd-bbaa-7d34a2d625b3/reverse
accept: application/json