global using Microsoft.EntityFrameworkCore;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using Accounting.Domain.Models;
global using System.Reflection;
global using Accounting.Domain.Models;
global using Accounting.Domain.VelueObjects;
global using Microsoft.EntityFrameworkCore.Metadata.Builders;
global using Microsoft.EntityFrameworkCore.Metadata.Builders;