# curl -i http://httpbin.org/ip
GET {{API_HostAddress}}/health

###

# curl -X 'GET' 
#  'https://localhost:6060/reports/balance-sheet?periodId=e44ed594-272c-4978-a3b5-11fb47e9ca12&companyId=41607051-4bd8-4a54-a5e2-cb713aef6ca2' 
#  -H 'accept: application/json'
GET {{API_HostAddress}}/reports/balance-sheet?periodId=e44ed594-272c-4978-a3b5-11fb47e9ca12&companyId=41607051-4bd8-4a54-a5e2-cb713aef6ca2
accept: application/json

###

